sudo: required
dist: xenial

language: php

php:
  - 7.2.34

addons:
  postgresql: "9.5"
  apt:
    update: true

before_script:
  - cp .env.travis .env
  - pecl install mailparse
  - psql -c 'create database evolution_users_test;' -U postgres
  - composer self-update
  - composer install --no-interaction
  - php artisan migrate
  - php artisan db:update-functions

script:
  - vendor/bin/phpunit
