language: php

php:
  - 7.0

before_script:
  - cp .env.travis .env
  - psql -c 'create database evolution_users_test;' -U postgres
  - composer self-update
  - composer install --no-interaction
  - php artisan migrate
  - php artisan db:update-functions

script:
  - vendor/bin/phpunit
